name: Weekly Engulfing Scan

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 3:00 PM IST (UTC+5:30)
  workflow_dispatch:  # Allows manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas requests

      - name: Run the Python script
        run: python engulfing_scan.py
